name: urbit-eventlog-lmdb
version: 0.10.4
license: MIT
license-file: LICENSE

library:
  source-dirs: lib
  ghc-options:
    - -Wall
    - -Werror
    - -Wno-type-defaults
    - -Wno-unused-matches
    - -Wno-name-shadowing
    - -Wno-unused-do-bind
    - -O2

dependencies:
  - base
  - classy-prelude
  - stm
  - rio
  - vector
  - bytestring
  - lmdb-static
  - conduit
  - racquire
  - urbit-noun-core
  - urbit-noun

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PatternSynonyms
  - QuasiQuotes
  - Rank2Types
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UnboxedTuples
  - UnicodeSyntax
  - ViewPatterns
